/* Painel DJUD — domínio e dados iniciais.
   Carregado antes de app.js. Não depende de nada. */

/* Coordenações. `full` é o valor gravado; `short` o exibido; `dot` a cor da seção.
   A ORDEM define a ordem das seções no quadro e o desempate da ordenação. */
const COORDS = [
  {full: "DIRETORA", short: "Diretora", dot: "#6B7280"},
  {full: "TRANSVERSAIS (afetam várias áreas)", short: "Transversais", dot: "#7C6BAF"},
  {full: "CGMED — Coordenação Médica e Farmacêutica", short: "CGMED", dot: "#2E8B8B"},
  {full: "CGAJUD — Análise e Monitoramento", short: "CGAJUD", dot: "#C77D3C"},
  {full: "CGLJUD — Logística Judicial", short: "CGLJUD", dot: "#3E7CB1"},
  {full: "CGPJUD — Ressarcimento pelos estados", short: "CGPJUD", dot: "#B0577A"},
  {full: "CGPO — Planejamento e Orçamento", short: "CGPO", dot: "#4E9A6B"},
  {full: "GABINETE da diretora (assessoria)", short: "Gabinete", dot: "#9A7B4F"},
];

/* Enums. Fonte única: os <option> e as regras de CSS derivam daqui.
   Ao acrescentar um valor, inclua também a regra correspondente em app.css. */
const PRIOS  = ["1", "2", "3", "A definir"];
const COMPS  = ["Baixa", "Média", "Alta", "Muito alta"];
const STATUS = ["Não iniciada", "Em andamento", "Concluída"];

/* Texto auxiliar mostrado sob o selo de prioridade no card. */
const PRIO_LABEL = { "1": "mais alta", "2": "intermediária", "3": "mais baixa", "A definir": "a definir" };

/* Carga inicial usada no modo demonstração e pelo botão "Reiniciar".
   No modo conectado quem manda é a planilha — isto aqui não é lido. */
const PRODUTOS = ["Painéis de tramitação","Medicamentos judicializados + UF","Estoque e logística (SISMAT)","Compras e atas","Ressarcimento aos estados","Depósitos judiciais","Orçamento (execução e projeção)","Preços de medicamentos","Reabertura (desabastecimento)","Automação do painel CGAJUD","Lista de processos sob demanda","Emergenciais (acesso externo)","Alertas (transversal)","Banco de Notas Técnicas (paralelo)","Banco de respostas / LAI","Extração de documentos do SEI (separado)"];
const PRAZOS   = ["Curto prazo","Médio prazo","Longo prazo","A definir"];
const PRAZO_KIND = { "Curto prazo":"curto", "Médio prazo":"medio", "Longo prazo":"longo", "A definir":"adef" };

const SEED = [
 {
  "id": "d01",
  "coord": "DIRETORA",
  "titulo": "Alerta de medicamentos emergenciais (pré-entrada)",
  "oque": "Avisar a compra urgente antes de o processo entrar no DJUD, para ganhar dias de prazo. Depende de acesso ao Sapiens/EPROC (Justiça/AGU) que ainda não temos.",
  "fonte": "Sapiens / EPROC (Justiça / AGU)",
  "acesso": "sem acesso hoje",
  "prio": "1",
  "comp": "Alta",
  "obs": "pedido da diretora",
  "warn": "sem acesso (Sapiens/EPROC)",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Emergenciais (acesso externo)",
  "prazo": "A definir"
 },
 {
  "id": "d02",
  "coord": "DIRETORA",
  "titulo": "Tempo do processo: entrada e por coordenação",
  "oque": "Medir quanto o processo leva na entrada e em cada coordenação (Portaria 7676, 30 dias).",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Baixa",
  "obs": "pedido da diretora",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Painéis de tramitação",
  "prazo": "Curto prazo"
 },
 {
  "id": "d03",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Recuperação dos dados históricos",
  "oque": "Reconstruir o histórico para permitir projeção de demanda e responder LAI.",
  "fonte": "Documentos de dentro do processo (SEI)",
  "acesso": "sem acesso hoje",
  "prio": "1",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d04",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Painel de preços-teto (CMED/PMVG)",
  "oque": "Preço-teto adaptado do DLOG. Nível 1 por caixa (baixa), nível 2 por unidade (média).",
  "fonte": "Tabela CMED (Anvisa)",
  "acesso": "fonte pública, disponível",
  "prio": "2",
  "comp": "Baixa",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Preços de medicamentos",
  "prazo": "Curto prazo"
 },
 {
  "id": "d05",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Consolidação dos depósitos (FUNDO)",
  "oque": "Repositório confiável de depósitos; comparar depósito × aquisição.",
  "fonte": "Sistema do fundo",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Depósitos judiciais",
  "prazo": "Médio prazo"
 },
 {
  "id": "d06",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Medicamentos mais judicializados (estado/perfil)",
  "oque": "Ranking por medicamento, estado e perfil; cruzar médico × medicamento.",
  "fonte": "RedMine (lista interna de processos); Documentos de dentro do processo (SEI)",
  "acesso": "depende de liberar o acesso; sem acesso hoje",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Medicamentos judicializados + UF",
  "prazo": "Médio prazo"
 },
 {
  "id": "d07",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Recorte por estado (UF) — dimensão reutilizável",
  "oque": "Deduzir o estado pelo nº CNJ e disponibilizar como dimensão para todos os painéis.",
  "fonte": "RedMine (lista interna de processos)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Baixa",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Medicamentos judicializados + UF",
  "prazo": "Curto prazo"
 },
 {
  "id": "d08",
  "coord": "TRANSVERSAIS (afetam várias áreas)",
  "titulo": "Alertas automáticos de prazo e pendências",
  "oque": "Alertas de compra parada, ata a vencer e prazo de resposta de 10 dias.",
  "fonte": "Compras.gov / PNCP; Web service do SEI (tramitação)",
  "acesso": "fonte pública, disponível; depende de liberar o acesso",
  "prio": "2",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Alertas (transversal)",
  "prazo": "Longo prazo"
 },
 {
  "id": "d09",
  "coord": "CGMED — Coordenação Médica e Farmacêutica",
  "titulo": "Produção por farmacêutico (+ fila furada)",
  "oque": "Produtividade por farmacêutico e detecção de quem pega os fáceis fora da ordem.",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Painéis de tramitação",
  "prazo": "Médio prazo"
 },
 {
  "id": "d10",
  "coord": "CGMED — Coordenação Médica e Farmacêutica",
  "titulo": "Dados do paciente organizados (endereço + peso)",
  "oque": "Repositório por paciente com o nº do processo como chave, compartilhado com a CGLJUD.",
  "fonte": "Documentos de dentro do processo (SEI)",
  "acesso": "sem acesso hoje",
  "prio": "3",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d11",
  "coord": "CGMED — Coordenação Médica e Farmacêutica",
  "titulo": "Repositório de preços de mercado (consultas semanais)",
  "oque": "Repositório onde os farmacêuticos alimentam/consultam o preço de mercado por medicamento, para padronizar o valor usado nos depósitos.",
  "fonte": "Fontes externas de consulta de preço (sites/farmácias); Planilhas das áreas (SharePoint)",
  "acesso": "consulta externa — sites a definir com a Fernanda; depende de liberar o acesso",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Preços de medicamentos",
  "prazo": "Médio prazo"
 },
 {
  "id": "d12",
  "coord": "CGAJUD — Análise e Monitoramento",
  "titulo": "Automatizar o painel existente (+ detalhamento)",
  "oque": "Automatizar a consolidação manual do painel da Gilda/Lara e permitir detalhar.",
  "fonte": "Planilhas das áreas (SharePoint); Web service do SEI (tramitação); RedMine (lista interna de processos)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Automação do painel CGAJUD",
  "prazo": "Médio prazo"
 },
 {
  "id": "d13",
  "coord": "CGAJUD — Análise e Monitoramento",
  "titulo": "Painel de intimações — coberto pelo SISDJUD",
  "oque": "Só papel/digitalização hoje. Interim: painel a partir da planilha do Andrei; futuro: SISDJUD.",
  "fonte": "SISDJUD (novo sistema do DJUD); Planilhas das áreas (SharePoint)",
  "acesso": "sistema em implantação; depende de liberar o acesso",
  "prio": "2",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d14",
  "coord": "CGAJUD — Análise e Monitoramento",
  "titulo": "Reabertura antes do desabastecimento",
  "oque": "Calcular a data provável de desabastecimento e alertar para reabrir o processo.",
  "fonte": "Planner (Microsoft); Planilhas das áreas (SharePoint)",
  "acesso": "acesso já disponível; depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Reabertura (desabastecimento)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d15",
  "coord": "CGAJUD — Análise e Monitoramento",
  "titulo": "Lista de processos sob demanda",
  "oque": "Exportação sob demanda: processos ativos/abertos + números.",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "3",
  "comp": "Baixa",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Lista de processos sob demanda",
  "prazo": "Curto prazo"
 },
 {
  "id": "d16",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Painel de estoque (SISMAT)",
  "oque": "Estoque por medicamento cruzado com pacientes ativos, consumo médio e ata vigente.",
  "fonte": "SISMAT (estoque / DLog)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Estoque e logística (SISMAT)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d17",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Correção / limpeza da base do SISMAT",
  "oque": "Separar aquisição × devolução, remover duplicidades, descrever saídas.",
  "fonte": "SISMAT (estoque / DLog)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Estoque e logística (SISMAT)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d18",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Remanejamento entre hospitais",
  "oque": "Trazer para o painel os medicamentos parados em hospitais.",
  "fonte": "SISMAT (estoque / DLog); Planilhas das áreas (SharePoint)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Estoque e logística (SISMAT)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d19",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Compras (DFDs) + prioritárias 414 e fracassos",
  "oque": "Painel de fase e urgência das compras, com recorte das prioritárias e o motivo dos fracassos.",
  "fonte": "Compras.gov / PNCP",
  "acesso": "fonte pública, disponível",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Compras e atas",
  "prazo": "Médio prazo"
 },
 {
  "id": "d20",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Saldo e vencimento das atas",
  "oque": "Saldo (comprado × executado) + alerta 6 meses antes do vencimento.",
  "fonte": "Compras.gov / PNCP",
  "acesso": "fonte pública, disponível",
  "prio": "2",
  "comp": "Baixa",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Compras e atas",
  "prazo": "Curto prazo"
 },
 {
  "id": "d21",
  "coord": "CGLJUD — Logística Judicial",
  "titulo": "Trocas a vencer e incineração",
  "oque": "Monitorar as cartas de troca e as incinerações.",
  "fonte": "SISMAT (estoque / DLog)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Estoque e logística (SISMAT)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d22",
  "coord": "CGPJUD — Ressarcimento pelos estados",
  "titulo": "Valor de ressarcimento a receber dos estados",
  "oque": "Quanto cada estado deve ressarcir à União — hoje atualizado à mão.",
  "fonte": "FNS / SMART; SISMAT (estoque / DLog); Sistema do fundo",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Ressarcimento aos estados",
  "prazo": "Médio prazo"
 },
 {
  "id": "d23",
  "coord": "CGPJUD — Ressarcimento pelos estados",
  "titulo": "Regras de cálculo do ressarcimento (Tema 234)",
  "oque": "Alíquota por tipo (oncológico ~20%), incorporado ou não, depósito × entrega.",
  "fonte": "Sistema do fundo",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Ressarcimento aos estados",
  "prazo": "Médio prazo"
 },
 {
  "id": "d24",
  "coord": "CGPJUD — Ressarcimento pelos estados",
  "titulo": "Relatório quinzenal automático",
  "oque": "Gerar o quadro que a ASE pede a cada 15 dias a partir do painel.",
  "fonte": "Sistema do fundo",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Ressarcimento aos estados",
  "prazo": "Médio prazo"
 },
 {
  "id": "d25",
  "coord": "CGPJUD — Ressarcimento pelos estados",
  "titulo": "Saldo dos repasses a parceiros (TEDs)",
  "oque": "Saldo e situação dos 6 TEDs, hoje acompanhados à mão no SEI.",
  "fonte": "Documentos de dentro do processo (SEI)",
  "acesso": "sem acesso hoje",
  "prio": "3",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d26",
  "coord": "CGPO — Planejamento e Orçamento",
  "titulo": "Orçamento gasto no ano (SIAFI)",
  "oque": "Quanto do orçamento já foi gasto no ano, no formato que a diretora usa.",
  "fonte": "SIAFI (orçamento)",
  "acesso": "depende de acesso — certificado do Ministério",
  "prio": "1",
  "comp": "Baixa",
  "obs": "ganho rápido",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Orçamento (execução e projeção)",
  "prazo": "Curto prazo"
 },
 {
  "id": "d27",
  "coord": "CGPO — Planejamento e Orçamento",
  "titulo": "Planilha de depósitos preenchida automaticamente",
  "oque": "Campos já preenchidos pelas coordenações anteriores; a CGPO só põe a data.",
  "fonte": "Planilhas das áreas (SharePoint)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Depósitos judiciais",
  "prazo": "Médio prazo"
 },
 {
  "id": "d28",
  "coord": "CGPO — Planejamento e Orçamento",
  "titulo": "Projeção do orçamento até o fim do ano",
  "oque": "Projetar o gasto até dezembro (itens > R$ 1 mi); alimenta o PLOA.",
  "fonte": "SIAFI (orçamento); Compras.gov / PNCP",
  "acesso": "depende de acesso — certificado do Ministério; fonte pública, disponível",
  "prio": "2",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Orçamento (execução e projeção)",
  "prazo": "Médio prazo"
 },
 {
  "id": "d29",
  "coord": "CGPO — Planejamento e Orçamento",
  "titulo": "Checagem de óbito antes do depósito",
  "oque": "Conferir por CPF se o paciente faleceu antes de liberar o depósito.",
  "fonte": "Receita Federal; SIM / DataSUS (óbitos); SIRC (registro civil)",
  "acesso": "acesso já disponível; depende de liberar o acesso; a explorar",
  "prio": "3",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Depósitos judiciais",
  "prazo": "Médio prazo"
 },
 {
  "id": "d30",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Criticidade das demandas externas (alerta)",
  "oque": "Classificar e alertar as demandas externas (PF, MP, parlamentares).",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Painéis de tramitação",
  "prazo": "Médio prazo"
 },
 {
  "id": "d31",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Acompanhamento das demandas da assessoria",
  "oque": "Painel das 3 assessoras: quem está com cada demanda, prazo e situação.",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Baixa",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Painéis de tramitação",
  "prazo": "Médio prazo"
 },
 {
  "id": "d32",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Análise das condenações por danos morais",
  "oque": "Condenações cruzadas com o tempo no DJUD e o tipo de medicamento.",
  "fonte": "Web service do SEI (tramitação)",
  "acesso": "depende de liberar o acesso",
  "prio": "2",
  "comp": "Alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d33",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Painel público de dados (LAI)",
  "oque": "Painel público com as informações mais pedidas na LAI.",
  "fonte": "Documentos de dentro do processo (SEI); RedMine (lista interna de processos)",
  "acesso": "sem acesso hoje; depende de liberar o acesso",
  "prio": "3",
  "comp": "Muito alta",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Extração de documentos do SEI (separado)",
  "prazo": "A definir"
 },
 {
  "id": "d34",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Banco de Notas Técnicas (SDJud)",
  "oque": "Banco de notas técnicas do SDJud — atenção: ≠ SISDJUD. Demanda do TCU/Conjur.",
  "fonte": "SDJud (banco de notas técnicas)",
  "acesso": "a definir",
  "prio": "A definir",
  "comp": "Média",
  "obs": "",
  "warn": "≠ SISDJUD · em paralelo",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Banco de Notas Técnicas (paralelo)",
  "prazo": "A definir"
 },
 {
  "id": "d35",
  "coord": "GABINETE da diretora (assessoria)",
  "titulo": "Banco de respostas / LAI (repositório pesquisável)",
  "oque": "Modelo de planilha/repositório pesquisável p/ as assessoras: saber se um tema já foi respondido e reusar a resposta.",
  "fonte": "Planilhas das áreas (SharePoint); SISDJUD (novo sistema do DJUD)",
  "acesso": "depende de liberar o acesso; sistema em implantação",
  "prio": "1",
  "comp": "Média",
  "obs": "",
  "warn": "",
  "status": "Não iniciada",
  "pct": 0,
  "produto": "Banco de respostas / LAI",
  "prazo": "Longo prazo"
 }
];

const SEED_PLANO = [{"ordem": 1, "produto": "Base de dados do projeto (fundação)", "prazo": "Curto prazo", "prioridade": "—", "complexidade": "—", "demandas": ["Importar o RedMine (nº do processo do SEI como chave) e as planilhas das áreas (recorte de 2025 em diante)"], "fonte": "RedMine + planilhas das áreas", "observacao": "Primeira ação de todas as entregas. Aproveita o trabalho manual já feito e destrava as entregas rápidas; conecta os demais produtos."}, {"ordem": 2, "produto": "Painéis de tramitação — tempo, produtividade, criticidade e assessoria", "prazo": "Médio prazo", "prioridade": "1 e 2", "complexidade": "Baixa a Média", "demandas": ["Tempo do processo: entrada e por coordenação (Portaria 7676) — prioridade 1", "Produção por farmacêutico (e detecção de fila furada) — prioridade 2", "Criticidade das demandas externas — alerta (PF, MP, parlamentares) — prioridade 1", "Acompanhamento das demandas da assessoria (quem está com o quê, prazo) — prioridade 2"], "fonte": "Web service do SEI (tramitação) — depende de liberar o acesso", "observacao": "Todos usam o mesmo dado (a tramitação do processo). Liberado o web service, o “tempo do processo” (prioridade 1, baixa complexidade) sai no curto prazo; os demais painéis derivam da mesma base."}, {"ordem": 3, "produto": "Medicamentos mais judicializados e recorte por estado (UF)", "prazo": "Curto prazo", "prioridade": "2", "complexidade": "Baixa a Média", "demandas": ["Medicamentos mais judicializados (por estado e perfil) — prioridade 2", "Recorte por estado (UF) como dimensão reutilizável — prioridade 2"], "fonte": "RedMine (lista interna) — dedução do estado pelo nº CNJ", "observacao": "É praticamente a mesma entrega: o recorte por UF é uma dimensão do ranking. Entrega parcial rápida com o RedMine de 2025 em diante; o histórico anterior fica para depois."}, {"ordem": 4, "produto": "Estoque e logística — SISMAT", "prazo": "Médio prazo", "prioridade": "1 e 2", "complexidade": "Média", "demandas": ["Painel de estoque (medicamento × pacientes ativos × consumo × ata) — prioridade 1", "Correção / limpeza da base do SISMAT — prioridade 1", "Remanejamento entre hospitais — prioridade 1", "Trocas a vencer e incineração — prioridade 2"], "fonte": "SISMAT (estoque / DLog) — depende de aprovação/acesso do DLog", "observacao": "Um só produto sobre a base do SISMAT: painel de estoque, limpeza dos dados, remanejamento (integra a planilha dos hospitais) e alerta de trocas/incineração. Depende da liberação do DLog."}, {"ordem": 5, "produto": "Compras e atas", "prazo": "Curto prazo", "prioridade": "2", "complexidade": "Baixa a Média", "demandas": ["Acompanhamento das compras (DFDs), com recorte das prioritárias “414” e análise de fracassos — prioridade 2", "Saldo e vencimento das atas (+ alerta 6 meses antes) — prioridade 2"], "fonte": "Compras.gov / PNCP — fonte pública, disponível", "observacao": "Mesma fonte pública. O saldo/vencimento de atas (baixa complexidade) sai antes; o monitoramento de compras e o recorte 414/fracassos derivam da mesma integração."}, {"ordem": 6, "produto": "Ressarcimento aos estados (CGPJUD)", "prazo": "Médio prazo", "prioridade": "1 e 2", "complexidade": "Alta", "demandas": ["Valor de ressarcimento a receber dos estados — prioridade 1", "Regras de cálculo do ressarcimento (Tema 234) — prioridade 2", "Relatório quinzenal automático para a Secretaria Executiva — prioridade 2"], "fonte": "FNS/SMART × SISMAT × sistema do fundo — depende de liberar o acesso", "observacao": "Um produto: consolida entregas (SISMAT) e depósitos (fundo), aplica as regras do Tema 234 e gera o quadro quinzenal a partir do mesmo painel."}, {"ordem": 7, "produto": "Depósitos judiciais", "prazo": "Médio prazo", "prioridade": "1 e 3", "complexidade": "Média a Alta", "demandas": ["Consolidação dos depósitos (repositório confiável; depósito × aquisição) — prioridade 1", "Planilha de depósitos preenchida automaticamente (a CGPO só põe a data) — prioridade 1", "Checagem de óbito antes do depósito (por CPF) — prioridade 3"], "fonte": "Sistema do fundo + planilhas das áreas + óbito (SIM/DataSUS, Receita Federal)", "observacao": "Reúne três demandas numa só planilha/painel: consolidar os depósitos do fundo, preencher automaticamente a planilha com os dados das áreas e trazer a checagem de óbito para dentro dela."}, {"ordem": 8, "produto": "Orçamento — execução e projeção (CGPO)", "prazo": "Curto prazo", "prioridade": "1 e 2", "complexidade": "Baixa a Média", "demandas": ["Orçamento gasto no ano (SIAFI), no formato da diretora — prioridade 1 · ganho rápido", "Projeção do orçamento até o fim do ano (itens > R$ 1 mi; alimenta o PLOA) — prioridade 2"], "fonte": "SIAFI (orçamento) + Compras.gov/PNCP — certificado do Ministério", "observacao": "A execução orçamentária (prioridade 1, baixa complexidade, base já existente) é ganho rápido — curto prazo. A projeção depende de definir a origem dos custos por medicamento."}, {"ordem": 9, "produto": "Preços de medicamentos", "prazo": "Curto prazo", "prioridade": "2", "complexidade": "Baixa a Média", "demandas": ["Painel de preços-teto (CMED/PMVG) — reaproveita o painel do DLog — prioridade 2", "Repositório de preços de mercado (consultas semanais dos farmacêuticos) — prioridade 2"], "fonte": "Tabela CMED (Anvisa, pública) + fontes externas de consulta de preço", "observacao": "O preço-teto (CMED) reaproveita a base que o DLog já tem — entrega rápida; o repositório de preço de mercado é um complemento (sites a definir com a área)."}, {"ordem": 10, "produto": "Reabertura antes do desabastecimento (CGAJUD)", "prazo": "Médio prazo", "prioridade": "1", "complexidade": "Média", "demandas": ["Calcular a data provável de desabastecimento e alertar para reabrir o processo — prioridade 1"], "fonte": "Planilhas das áreas + Planner (Microsoft) — acesso já disponível", "observacao": "Viável sem extração de documentos: usa as planilhas e o Planner que as equipes já mantêm para calcular a data-limite e disparar o alerta."}, {"ordem": 11, "produto": "Lista de processos sob demanda (CGAJUD)", "prazo": "Curto prazo", "prioridade": "3", "complexidade": "Baixa", "demandas": ["Exportação sob demanda dos processos ativos/abertos + números — prioridade 3"], "fonte": "RedMine / tramitação do SEI", "observacao": "Entrega simples (baixa complexidade), embora de prioridade menor — pode sair cedo por ser rápida."}, {"ordem": 12, "produto": "Alerta de medicamentos emergenciais (pré-entrada)", "prazo": "A definir", "prioridade": "1", "complexidade": "Alta", "demandas": ["Avisar a compra urgente antes de o processo entrar no DJUD — prioridade 1 (pedido da diretora)"], "fonte": "Sapiens / EPROC (Justiça/AGU) — sem acesso hoje", "observacao": "Prioridade da direção, mas depende de acesso externo (Sapiens/EPROC), que ainda não temos. Não é extração de documentos do SEI — é articulação política (Conjur/procuradoria). Prazo em aberto até a liberação."}, {"ordem": 13, "produto": "Alertas automáticos de prazo e pendências (transversal)", "prazo": "Longo prazo", "prioridade": "2", "complexidade": "Muito alta", "demandas": ["Camada de alerta: compra parada, ata a vencer, prazo de resposta de 10 dias — prioridade 2"], "fonte": "Depende das bases (tramitação e compras) consolidadas", "observacao": "Só faz sentido depois que as bases estiverem consolidadas — portanto, horizonte mais longo."}, {"ordem": 14, "produto": "Banco de Notas Técnicas (SDJud) — trilha paralela", "prazo": "A definir", "prioridade": "A definir", "complexidade": "Média", "demandas": ["Banco de notas técnicas do SDJud (≠ SISDJUD) — demanda do TCU/Conjur"], "fonte": "SDJud (banco de notas técnicas)", "observacao": "Distinta do SISDJUD. Corre em paralelo e depende de alinhamento próprio; prioridade a definir."}, {"ordem": 15, "produto": "Banco de respostas / LAI (repositório pesquisável)", "prazo": "Longo prazo", "prioridade": "1", "complexidade": "Média", "demandas": ["Repositório pesquisável de respostas para as assessoras — prioridade 1"], "fonte": "Planilhas das áreas (SharePoint); futuro SISDJUD", "observacao": "Não será desenvolvido um sistema à parte: uma vez pronta a base e o painel público, a consulta às respostas anteriores fica atendida. Tratado como decorrência do painel público."}, {"ordem": 16, "produto": "Extração de documentos do SEI (separado)", "prazo": "A definir", "prioridade": "—", "complexidade": "Muito alta", "demandas": ["Recuperação dos dados históricos", "Dados do paciente organizados (peso, altura, endereço)", "Painel de intimações (OCR/escaneados ou acesso ao Eproc)", "Saldo dos repasses a parceiros (TEDs)", "Painel público de dados (LAI)", "Análise das condenações por danos morais (origem a definir)"], "fonte": "Conteúdo de dentro dos documentos do processo (SEI)", "observacao": "Fora do plano por ora: exigem ler o conteúdo de dentro dos documentos do processo (não só a tramitação). Frente mais incerta, em validação técnica com o Departamento; sem compromisso de prazo até confirmar o acesso ao serviço de extração de documentos."}];
